# Generated by Django 2.2 on 2020-04-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_auto_20200415_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='keys',
            field=models.CharField(max_length=5000),
        ),
    ]
