# Generated by Django 2.2 on 2020-04-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_auto_20200416_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='a_key',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='b_key',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='c_key',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='d_key',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=5000),
        ),
    ]
